<a href="https://colab.research.google.com/github/austin-1980/Python-class/blob/main/11%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C(2026199444%EC%8B%A0%ED%98%84%EC%A7%81)_20260513161247.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a= np.arange(6)
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a=np.array([[1,2,3],
           [4,5,6]])
a.shape

(2, 3)

In [5]:
a[1,1]

np.int64(5)

In [6]:
a=np.array([1,2,3,4,5,6])

In [7]:
a[0]

np.int64(1)

In [8]:
a[0]=10

In [9]:
a

array([10,  2,  3,  4,  5,  6])

In [10]:
a[:3]

array([10,  2,  3])

In [11]:
b=a[3:]

In [12]:
b

array([4, 5, 6])

In [13]:
b[0]=40

In [14]:
a

array([10,  2,  3, 40,  5,  6])

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[1,3]

np.int64(8)

In [18]:
a.ndim

2

In [19]:
a.shape

(3, 4)

In [20]:
len(a.shape)==a.ndim

True

In [21]:
a.size

12

In [22]:
import math

In [23]:
a.size==math.prod(a.shape)

True

In [24]:
a.dtype

dtype('int64')

In [25]:
np.zeros(2)

array([0., 0.])

In [26]:
np.ones(2)

array([1., 1.])

In [27]:
np.empty(2)

array([1., 1.])

In [28]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [29]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
x=np.ones(2,dtype=np.int64)

In [31]:
x

array([1, 1])

In [32]:
arr=np.array([2,1,5,3,7,4,6,8])

In [33]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [35]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])


In [36]:
np.concatenate((b,a))

array([5, 6, 7, 8, 1, 2, 3, 4])

In [37]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [38]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [41]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [42]:
array_example.ndim

3

In [43]:
array_example.size

24

In [44]:
array_example.shape

(3, 2, 4)

In [45]:
a=np.arange(6)

In [46]:
print(a)

[0 1 2 3 4 5]


In [47]:
b=a.reshape(3,2)

In [48]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [49]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [51]:
a2=a[np.newaxis,:]

In [52]:
a2.shape

(1, 6)

In [53]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [54]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [55]:
c

array([[1, 2, 3, 4, 5, 6]])

In [56]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [57]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [58]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [59]:
data[1]

np.int64(2)

In [60]:
data[0:2]

array([1, 2])

In [61]:
data[1:]

array([2, 3])

In [62]:
data[-2:]

array([2, 3])

In [63]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [64]:
print(a[a<5])

[1 2 3 4]


In [65]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [66]:
b>5

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True]])

In [67]:
five_up=(a>=5)

In [68]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [69]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [70]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [71]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [72]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
b= np.nonzero(a<5)

In [74]:
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [75]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [76]:
print(a[b])

[1 2 3 4]


In [77]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [78]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [80]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [81]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [82]:
np.concatenate((a1,a2),axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [83]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [85]:
np.hsplit(x, 3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [86]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [87]:
b2=a.copy()

In [88]:
b2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
a[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [91]:
data - ones


array([0, 1])

In [92]:
data * data


array([1, 4])

In [93]:
data / data

array([1., 1.])

In [94]:
len(b2)

10

In [95]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [96]:
b = np.array([[1, 1], [2, 2]])

In [97]:
b.sum(axis=0)

array([3, 3])

In [98]:
b.sum(axis=1)

array([2, 4])

In [99]:
a*2

array([2, 4, 6, 8])

In [100]:
b*3

array([[3, 3],
       [6, 6]])

In [101]:
data = np.array([1, 2, 3])
data.max()


np.int64(3)

In [102]:

data.sum()

np.int64(6)

In [103]:
data.min()

np.int64(1)

In [104]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [105]:
a.sum()

np.float64(4.8595784)

In [106]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [107]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:

data[0:2,0:]

array([[1, 2],
       [3, 4]])

In [110]:
data.max()

np.int64(6)

In [111]:
data.min()

np.int64(1)

In [112]:
data.sum()

np.int64(21)

In [113]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data


array([[1, 2],
       [5, 3],
       [4, 6]])

In [114]:
data.max(axis=0)


array([5, 6])

In [115]:
data.max(axis=1)

array([2, 5, 6])

In [116]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [117]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [118]:
np.ones(3)


array([1., 1., 1.])

In [119]:
np.zeros(3)


array([0., 0., 0.])

In [120]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.80642667, 0.72205958, 0.92151493])

In [121]:
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [122]:
np.zeros((3, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [123]:
rng.random((3, 2))

array([[0.74943661, 0.47987504],
       [0.65533985, 0.34262021],
       [0.67865302, 0.07761622]])

In [124]:
rng.integers(5, size=(2, 4))

array([[2, 4, 3, 2],
       [2, 0, 0, 0]])

In [125]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [126]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [127]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [128]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [129]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [130]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [131]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
print(indices)


[0 1 2]


In [133]:
print(occurrence_count)

[2 1 1]


In [134]:
data.reshape(2, 3)


ValueError: cannot reshape array of size 4 into shape (2,3)

In [135]:
data.reshape(3, 2)

ValueError: cannot reshape array of size 4 into shape (3,2)

In [136]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [137]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [138]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [139]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [140]:
reversed_arr = np.flip(arr)

In [141]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [142]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [143]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [144]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [145]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [146]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [147]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [148]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [149]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [150]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [151]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array


[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [152]:
print(a2)  # New array

[98  2  3  4  5  6  7  8  9 10 11 12]
